### ISSUE TITLE
Do you still want an LTS fork?

### ISSUE THREAD

**Issue by Flyingmana** [OpenMage/organizational#4]
as Magento recently announced an extended security lifetime for Magento1, the question is, do you still need or want an LTS fork of it.

**Comment by addison74** [comment]
In the last years community proved it can solve Magento issues faster and better than Magento maintenance team. Just look at the version 1.9.3.3, thanks to Stackexchange discussions the issues were fixed very quick. For security issues I give credits to Magento team, but for bugs in the code no chance. I reported many bugs in Bug Tracker over the years which are still in the code and they did not take in consideration them even I provided the fixes.

**Comment by niclashoyer** [comment]
We just hit a core bug today that is AFAIK not fixed yet by official Magento releases:

https://github.com/OpenMage/magento-lts/issues/80

I just applied the fix from the corresponding PR and was done. Otherwise I would have to get into debugging this from the ground up. We plan to switch some of our customers to the LTS fork in the near future, because managing core bugfixes by hand is really hard.

**Comment by sreichel** [comment]
Short answer: **YES**, of course!

I use this fork for all projects i'm involved, because age old bugs are fixes, some improvements are added I dont want miss. With this additions LTS is always one step ahead official releases ...

The very nice thing is that not every PR is added quickly (some take a bit to long, but it doesn't hurt) ... with current review system two person have to validate this first, so just approved thing will be added ....

**Comment by Flyingmana** [comment]
observing the recent activity of this project, the answer is indeed Yes
